public enum TokenType {
    NUMBER, STRING, TRUE, FALSE, NIL, IDENTIFIER, AND, CLASS, ELSE, FOR, FUN, IF,
    OR, PRINT, RETURN, SUPER, THIS, VAR, WHILE, LEFT_PAREN, RIGHT_PAREN,
    PLUS, MINUS, STAR, SLASH, EOF
}