public enum TokenType {
    NUMBER, STRING, TRUE, FALSE, NIL, IDENTIFIER, AND, CLASS, ELSE, FOR, FUN, IF, PLUS, MINUS, STAR, SLASH, EOF, OR, PRINT, RETURN, SUPER, 
    THIS, VAR, WHILE, LEFT_PAREN, RIGHT_PAREN, EQUAL_EQUAL, BANG_EQUAL, LESS, LESS_EQUAL, GREATER, GREATER_EQUAL, LEFT_BRACE, RIGHT_BRACE, 
    COMMA, DOT, SEMICOLON, EQUAL, BANG, ERROR 
}
