public enum TokenType {
    NUMBER, STRING, TRUE, FALSE, NIL, IDENTIFIER, AND, CLASS, ELSE, FOR, FUN, IF,
    OR, PRINT, RETURN, SUPER, THIS, VAR, WHILE, LEFT_PAREN, RIGHT_PAREN,
    PLUS, MINUS, STAR, SLASH, EOF
}
//enum TokenType {
//    LEFT_PAREN, RIGHT_PAREN, PLUS, MINUS, STAR, SLASH, EQUAL_EQUAL, BANG_EQUAL, LESS, LESS_EQUAL, GREATER, GREATER_EQUAL,
//    NUMBER, STRING, TRUE, FALSE, NIL, EOF
//}